In [1]:
import numpy as np

In [2]:
arr = np.random.randn(16)
arr

array([-0.38504056, -0.98180744,  0.98886463, -0.78085391,  1.3977566 ,
        0.58313372,  0.4162447 ,  0.32963082, -0.17863436,  0.59076994,
        0.0573346 ,  1.33723834,  0.3755999 , -1.47372271,  1.54174595,
       -0.07509979])

In [8]:
arr = arr.reshape(4,4)
arr

array([[-0.38504056, -0.98180744,  0.98886463, -0.78085391],
       [ 1.3977566 ,  0.58313372,  0.4162447 ,  0.32963082],
       [-0.17863436,  0.59076994,  0.0573346 ,  1.33723834],
       [ 0.3755999 , -1.47372271,  1.54174595, -0.07509979]])

In [11]:
arr = arr.transpose()
arr

array([[-0.38504056, -0.98180744,  0.98886463, -0.78085391],
       [ 1.3977566 ,  0.58313372,  0.4162447 ,  0.32963082],
       [-0.17863436,  0.59076994,  0.0573346 ,  1.33723834],
       [ 0.3755999 , -1.47372271,  1.54174595, -0.07509979]])

In [13]:
arr.reshape(2,8)

array([[-0.38504056, -0.98180744,  0.98886463, -0.78085391,  1.3977566 ,
         0.58313372,  0.4162447 ,  0.32963082],
       [-0.17863436,  0.59076994,  0.0573346 ,  1.33723834,  0.3755999 ,
        -1.47372271,  1.54174595, -0.07509979]])